#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$(cd "$SCRIPT_DIR/../../contracts" && pwd)"
OUTPUT="$SCRIPT_DIR/../src/abis.ts"

cat > "$OUTPUT" << 'HEADER'
// AUTO-GENERATED by packages/shared/scripts/generate-abis-inline.sh
// Do not edit manually.

import type { Abi } from 'viem';

HEADER

for json_file in "$CONTRACTS_DIR"/src/abis/*.json; do
  name="$(basename "$json_file" .json)"
  var_name="$(echo "${name}" | sed 's/^[A-Z]/\L&/')Abi"
  if command -v jq &>/dev/null; then
    json_content=$(jq -c '.' "$json_file")
  else
    json_content=$(tr -d '\n' < "$json_file")
  fi
  echo "export const ${var_name}: Abi = ${json_content} as const;" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
done

cat >> "$OUTPUT" << 'FOOTER'
export const ABIS = {
  profileRegistry: profileRegistryAbi,
  activityRegistry: activityRegistryAbi,
  territoryRegistry: territoryRegistryAbi,
  seasonManager: seasonManagerAbi,
  achievementRegistry: achievementRegistryAbi,
  challengeRegistry: challengeRegistryAbi,
  territoryNFT: territoryNFTAbi,
  moveToEarnToken: moveToEarnTokenAbi,
  groupRegistry: groupRegistryAbi,
} as const;

export type ContractName = keyof typeof ABIS;
FOOTER

echo "Generated $OUTPUT"
